apiVersion: v1
kind: Secret
metadata:
  name: jfrogcred
  namespace: iso
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJpc21haWxpbGljYS5qZnJvZy5pbyI6IHsKCQkJImF1dGgiOiAiTWpFeE5EVXdNREl5UUd4b2RTNWxaSFV1ZEhJNlVtOXRZVzV5WldsbmJuTXlPU0U9IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson